--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    run: kubernetes-dashboard
  name: kubernetes-dashboard-external
  namespace: kubernetes-dashboard
spec: 
  ports: 
    - 
      port: 443
      protocol: TCP
      targetPort: 9090
  selector: 
    k8s-app: kubernetes-dashboard
  type: LoadBalancer
